#!/usr/bin/env python3
"""Legacy helper: build a temporary Markdown file from rendered Pudding HTML.

Do not use this for editable Pudding admin content. Current Pudding CaseStudy
content should be synced from source Markdown with `pudding sync`.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def split_frontmatter(text: str) -> tuple[str, str]:
    if not text.startswith("---\n"):
        return "", text
    end = text.find("\n---\n", 4)
    if end == -1:
        return "", text
    return text[: end + 5], text[end + 5 :]


def build_sync_copy(source_md: Path, rendered_html: Path, output_md: Path) -> Path:
    frontmatter, _body = split_frontmatter(source_md.read_text(encoding="utf-8"))
    html = rendered_html.read_text(encoding="utf-8").strip()
    output_md.parent.mkdir(parents=True, exist_ok=True)
    content = f"{frontmatter}\n{html}\n" if frontmatter else html + "\n"
    output_md.write_text(content, encoding="utf-8")
    return output_md


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source_md", help="Original Markdown article; only frontmatter is reused")
    parser.add_argument("rendered_html", help="Pudding target HTML generated by render_markdown.py")
    parser.add_argument("output_md", help="Temporary Markdown file for legacy HTML-content sync")
    args = parser.parse_args()
    print(
        "[build_pudding_sync_copy] WARNING: legacy HTML-content helper; "
        "do not use for editable Pudding admin content.",
        file=sys.stderr,
    )
    print(build_sync_copy(Path(args.source_md), Path(args.rendered_html), Path(args.output_md)))


if __name__ == "__main__":
    main()
